[package]
name = "kd-forest"
version = "2.0.0"
authors = ["Tavian Barnes <tavianator@tavianator.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
image = "0.23.4"
ordered-float = "1.0.2"
rand = "0.7.3"
rand_pcg = "0.2.1"
term = "0.6.1"
